import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Generated from the docs/ folder structure - category order comes from each
// folder's _category_.json, page order within a category from sidebar_position
// frontmatter. See CLAUDE.md before adding a page.
const sidebars: SidebarsConfig = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
